**Muhammad Naufal Erza Farandi**

**A11.2021.13861**

In [3]:
import numpy as np
import math

# **Matriks Translasi**

In [23]:
def translasi(matriks, tx, ty):
    translasiMatrix = np.array([[1, 0, tx],
                                [0, 1, ty],
                                [0, 0, 1]])
    hasil = np.dot(translasiMatrix, matriks)
    return hasil

def main():
    matriksAwal = np.array([[1, 0, 2],
                            [0, 1, 5],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    tx = int(input("Masukkan nilai tx untuk translasi: "))
    ty = int(input("Masukkan nilai ty untuk translasi: "))

    matriksHasil = translasi(matriksAwal, tx, ty)

    print("Matriks setelah translasi:")
    print(matriksHasil)

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 2]
 [0 1 5]
 [0 0 1]]
Masukkan nilai tx untuk translasi: 4
Masukkan nilai ty untuk translasi: 6
Matriks setelah translasi:
[[ 1  0  6]
 [ 0  1 11]
 [ 0  0  1]]


# **Matriks Skalar**

In [31]:
def skalar(matriks, sx, sy):
    skalarMatrix = np.array([[sx, 0, 0],
                             [0, sy, 0],
                             [0, 0, 1]])

    hasil = np.dot(skalarMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 8],
                            [0, 1, 2],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    skalarX = int(input("Masukkan nilai skalar sx: "))
    skalarY = int(input("Masukkan nilai skalar sy: "))

    hasilSkalar = skalar(matriksAwal, skalarX, skalarY)

    print("Matriks setelah operasi skalar:")
    for row in hasilSkalar:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 8]
 [0 1 2]
 [0 0 1]]
Masukkan nilai skalar sx: 2
Masukkan nilai skalar sy: 2
Matriks setelah operasi skalar:
[2, 0, 16]
[0, 2, 4]
[0, 0, 1]


# **Matriks Rotasi**

In [18]:
def rotasiTotal(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[math.cos(totalRad), -math.sin(totalRad), 0],
                             [math.sin(totalRad), math.cos(totalRad), 0],
                             [0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 2],
                            [0, 1, 6],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    hasilRotasi = rotasiTotal(matriksAwal, sudutTotal, 0)

    print("Matriks setelah rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 2]
 [0 1 6]
 [0 0 1]]
Masukkan sudut rotasi total (dalam derajat): 45
Matriks setelah rotasi:
[0.71, -0.71, -2.83]
[0.71, 0.71, 5.66]
[0.0, 0.0, 1.0]
