# **Muhammad Naufal Erza Farandi**

# **A11.2021.13861**

NIM : abcde = 13861

P1 (a, b) = (1, 3)

P2 (c, d) = (8, 6)

In [ ]:
import numpy as np
import math

**Refleksi Terhadap Sumbu X**

In [ ]:
def refleksiSumbuX():
    matrix = np.array([[1, 0, 0],
                       [0, -1, 0],
                       [0, 0, 1]])
    return matrix

def apply_reflection(matrix, vector):
    resultVector = np.dot(matrix, vector)
    return resultVector

refleksiMatrix = refleksiSumbuX()

inputP1 = np.array([1, 3, 1])
inputP2 = np.array([6, 1, 1])

outputP1 = apply_reflection(refleksiMatrix, inputP1)
outputP2 = apply_reflection(refleksiMatrix, inputP2)

print("P1:", inputP1)
print("P2:", inputP2)
print("Refleksi P1:", outputP1)
print("Refleksi P2:", outputP2)

P1: [1 3 1]
P2: [6 1 1]
Refleksi P1: [ 1 -3  1]
Refleksi P2: [ 6 -1  1]


**Refleksi Terhadap Sumbu Y**

In [ ]:
def refleksiSumbuY():
    matrix = np.array([[-1, 0, 0],
                       [0, 1, 0],
                       [0, 0, 1]])
    return matrix

def apply_reflection(matrix, vector):
    resultVector = np.dot(matrix, vector)
    return resultVector

refleksiMatrix = refleksiSumbuY()

inputP1 = np.array([1, 3, 1])
inputP2 = np.array([6, 1, 1])

outputP1 = apply_reflection(refleksiMatrix, inputP1)
outputP2 = apply_reflection(refleksiMatrix, inputP2)

print("P1:", inputP1)
print("P2:", inputP2)
print("Refleksi P1:", outputP1)
print("Refleksi P2:", outputP2)

P1: [1 3 1]
P2: [6 1 1]
Refleksi P1: [-1  3  1]
Refleksi P2: [-6  1  1]


**Refleksi Terhadap Sumbu XY**

In [ ]:
def refleksiSumbuXY():
    matrix = np.array([[-1, 0, 0],
                       [0, -1, 0],
                       [0, 0, 1]])
    return matrix

def apply_reflection(matrix, vector):
    resultVector = np.dot(matrix, vector)
    return resultVector

refleksiMatrix = refleksiSumbuXY()

inputP1 = np.array([1, 3, 1])
inputP2 = np.array([6, 1, 1])

outputP1 = apply_reflection(refleksiMatrix, inputP1)
outputP2 = apply_reflection(refleksiMatrix, inputP2)

print("P1:", inputP1)
print("P2:", inputP2)
print("Refleksi P1:", outputP1)
print("Refleksi P2:", outputP2)

P1: [1 3 1]
P2: [6 1 1]
Refleksi P1: [-1 -3  1]
Refleksi P2: [-6 -1  1]


**Translasi**

In [ ]:
def translasi(matriks, tx, ty):
    translasiMatrix = np.array([[1, 0, tx],
                                [0, 1, ty],
                                [0, 0, 1]])
    hasil = np.dot(translasiMatrix, matriks)
    return hasil

def main():

    x = int(input("Masukkan nilai x : "))
    y = int(input("Masukkan nilai y : "))
    matriksAwal = np.array([[1, 0, x],
                            [0, 1, y],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    tx = int(input("Masukkan nilai tx untuk translasi: "))
    ty = int(input("Masukkan nilai ty untuk translasi: "))

    matriksHasil = translasi(matriksAwal, tx, ty)

    print("Matriks setelah translasi:")
    print(matriksHasil)

if __name__ == "__main__":
    main()


Masukkan nilai x : 1
Masukkan nilai y : 3
Matriks awal:
[[1 0 1]
 [0 1 3]
 [0 0 1]]
Masukkan nilai tx untuk translasi: 8
Masukkan nilai ty untuk translasi: 6
Matriks setelah translasi:
[[1 0 9]
 [0 1 9]
 [0 0 1]]


**Skalar**

In [ ]:
def skalar(matriks, sx, sy):
    skalarMatrix = np.array([[sx, 0, 0],
                             [0, sy, 0],
                             [0, 0, 1]])

    hasil = np.dot(skalarMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 1],
                            [0, 1, 3],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    skalarX = int(input("Masukkan nilai skalar sx: "))
    skalarY = int(input("Masukkan nilai skalar sy: "))

    hasilSkalar = skalar(matriksAwal, skalarX, skalarY)

    print("Matriks setelah operasi skalar:")
    for row in hasilSkalar:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 1]
 [0 1 3]
 [0 0 1]]
Masukkan nilai skalar sx: 2
Masukkan nilai skalar sy: 2
Matriks setelah operasi skalar:
[2, 0, 2]
[0, 2, 6]
[0, 0, 1]


**Rotasi**

In [ ]:
def rotasiTotal(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[math.cos(totalRad), -math.sin(totalRad), 0],
                             [math.sin(totalRad), math.cos(totalRad), 0],
                             [0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 2],
                            [0, 1, 6],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    hasilRotasi = rotasiTotal(matriksAwal, sudutTotal, 0)

    print("Matriks setelah rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 2]
 [0 1 6]
 [0 0 1]]
Masukkan sudut rotasi total (dalam derajat): 45
Matriks setelah rotasi:
[0.71, -0.71, -2.83]
[0.71, 0.71, 5.66]
[0.0, 0.0, 1.0]


**COMPOSITE**

**Translasi + Refleksi Terhadap Sumbu X**

In [ ]:
def refleksiSumbuX():
    matrix = np.array([[1, 0, 0],
                       [0, -1, 0],
                       [0, 0, 1]])
    return matrix

def translasi(tx, ty):
    matrix = np.array([[1, 0, tx],
                       [0, 1, tx],
                       [0, 0, 1]])
    return matrix

def apply_transformation(matrix, vector):
    resultVector = np.dot(matrix, vector)
    return resultVector

translasiMatrix = translasi(8, 6)
refleksiMatrix = refleksiSumbuX()

inputP1 = np.array([1, 3, 1])
inputP2 = np.array([6, 1, 1])

outputP1_setelah_translasi = apply_transformation(translasiMatrix, inputP1)
outputP2_setelah_translasi = apply_transformation(translasiMatrix, inputP2)

outputP1 = apply_transformation(refleksiMatrix, outputP1_setelah_translasi)
outputP2 = apply_transformation(refleksiMatrix, outputP2_setelah_translasi)

print("P1:", inputP1)
print("P2:", inputP2)
print("Translasi P1:", outputP1_setelah_translasi)
print("Translasi P2:", outputP2_setelah_translasi)
print("Refleksi setelah translasi P1:", outputP1)
print("Refleksi setelah translasi P2:", outputP2)


P1: [1 3 1]
P2: [6 1 1]
Translasi P1: [ 9 11  1]
Translasi P2: [14  9  1]
Refleksi setelah translasi P1: [  9 -11   1]
Refleksi setelah translasi P2: [14 -9  1]


**Skalar + Refleksi Terhadap Sumbu Y**

In [ ]:
def refleksiSumbuX():
    matrix = np.array([[-1, 0, 0],
                       [0, 1, 0],
                       [0, 0, 1]])
    return matrix

def skalar(sx, sy):
    matrix = np.array([[sx, 0, 0],
                       [0, sy, 0],
                       [0, 0, 1]])
    return matrix

def apply_transformation(matrix, vector):
    resultVector = np.dot(matrix, vector)
    return resultVector

MatrixSkalar = translasi(2, 2)
refleksiMatrix = refleksiSumbuX()

inputP1 = np.array([1, 3, 1])
inputP2 = np.array([6, 1, 1])

outputP1Skalar = apply_transformation(translasiMatrix, inputP1)
outputP2Skalar = apply_transformation(translasiMatrix, inputP2)

outputP1 = apply_transformation(refleksiMatrix, outputP1_setelah_translasi)
outputP2 = apply_transformation(refleksiMatrix, outputP2_setelah_translasi)

print("P1:", inputP1)
print("P2:", inputP2)
print("Translasi P1:", outputP1Skalar)
print("Translasi P2:", outputP2Skalar)
print("Refleksi setelah translasi P1:", outputP1)
print("Refleksi setelah translasi P2:", outputP2)


P1: [1 3 1]
P2: [6 1 1]
Translasi P1: [ 9 11  1]
Translasi P2: [14  9  1]
Refleksi setelah translasi P1: [-9 11  1]
Refleksi setelah translasi P2: [-14   9   1]


**Translasi + Rotasi**

In [ ]:
def translasi(matriks, tx, ty):
    translasiMatrix = np.array([[1, 0, tx],
                                [0, 1, ty],
                                [0, 0, 1]])
    hasil = np.dot(translasiMatrix, matriks)
    return hasil

def rotasiTotal(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[math.cos(totalRad), -math.sin(totalRad), 0],
                             [math.sin(totalRad), math.cos(totalRad), 0],
                             [0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    x = int(input("Masukkan nilai x : "))
    y = int(input("Masukkan nilai y : "))
    matriksAwal = np.array([[1, 0, x],
                            [0, 1, y],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    tx = int(input("Masukkan nilai tx untuk translasi: "))
    ty = int(input("Masukkan nilai ty untuk translasi: "))

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    matriksSetelahTranslasi = translasi(matriksAwal, tx, ty)

    hasilRotasi = rotasiTotal(matriksSetelahTranslasi, sudutTotal, 0)

    print("Matriks setelah translasi dan rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Masukkan nilai x : 1
Masukkan nilai y : 3
Matriks awal:
[[1 0 1]
 [0 1 3]
 [0 0 1]]
Masukkan nilai tx untuk translasi: 8
Masukkan nilai ty untuk translasi: 6
Masukkan sudut rotasi total (dalam derajat): 90
Matriks setelah translasi dan rotasi:
[0.0, -1.0, -9.0]
[1.0, 0.0, 9.0]
[0.0, 0.0, 1.0]


**Skalar + Rotasi**

In [ ]:
def skalar(matriks, sx, sy):
    translasiMatrix = np.array([[sx, 0, 0],
                                [0, sy, 0],
                                [0, 0, 1]])
    hasil = np.dot(translasiMatrix, matriks)
    return hasil

def rotasiTotal(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[math.cos(totalRad), -math.sin(totalRad), 0],
                             [math.sin(totalRad), math.cos(totalRad), 0],
                             [0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    x = int(input("Masukkan nilai x : "))
    y = int(input("Masukkan nilai y : "))
    matriksAwal = np.array([[1, 0, x],
                            [0, 1, y],
                            [0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    sx = int(input("Masukkan nilai sx untuk Skalar: "))
    sy = int(input("Masukkan nilai sy untuk Skalar: "))

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    matriksSetelahSkalar = skalar(matriksAwal, sx, sy)

    hasilRotasi = rotasiTotal(matriksSetelahSkalar, sudutTotal, 0)

    print("Matriks setelah skalar dan rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Masukkan nilai x : 1
Masukkan nilai y : 3
Matriks awal:
[[1 0 1]
 [0 1 3]
 [0 0 1]]
Masukkan nilai sx untuk Skalar: 2
Masukkan nilai sy untuk Skalar: 2
Masukkan sudut rotasi total (dalam derajat): 90
Matriks setelah translasi dan rotasi:
[0.0, -2.0, -6.0]
[2.0, 0.0, 2.0]
[0.0, 0.0, 1.0]
