# **Matriks Transformasi 3D**

In [10]:
import numpy as np
import math

**Translasi**

In [ ]:
def translasi(matriks, tx, ty, tz):
    translasiMatrix = np.array([[1, 0, 0, tx],
                                [0, 1, 0, ty],
                                [0, 0, 1, ty],
                                [0, 0, 0, 1]])
    hasil = np.dot(translasiMatrix, matriks)
    return hasil

def main():
    matriksAwal = np.array([[1, 0, 0, 2],
                            [0, 1, 0, 5],
                            [0, 0, 1, 4],
                            [0, 0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    tx = int(input("Masukkan nilai tx untuk translasi: "))
    ty = int(input("Masukkan nilai ty untuk translasi: "))
    tz = int(input("Masukkan nilai tz untuk translasi: "))

    matriksHasil = translasi(matriksAwal, tx, ty, tz)

    print("Matriks setelah translasi:")
    print(matriksHasil)

if __name__ == "__main__":
    main()

Matriks awal:
[[1 0 0 2]
 [0 1 0 5]
 [0 0 1 4]
 [0 0 0 1]]
Masukkan nilai tx untuk translasi: 1
Masukkan nilai ty untuk translasi: 1
Masukkan nilai tz untuk translasi: 1
Matriks setelah translasi:
[[1 0 0 3]
 [0 1 0 6]
 [0 0 1 5]
 [0 0 0 1]]


**Rotasi**

In [9]:
def skalar(matriks, sx, sy, sz):
    skalarMatrix = np.array([[sx, 0, 0, 0],
                             [0, sy, 0, 0],
                             [0, 0, sz, 0],
                             [0, 0, 0, 1]])

    hasil = np.dot(skalarMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 0, 2],
                            [0, 1, 0, 5],
                            [0, 0, 1, 4],
                            [0, 0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    s = int(input("Masukkan nilai skalar: "))

    hasilSkalar = skalar(matriksAwal, s, s, s)

    print("Matriks setelah operasi skalar:")
    for row in hasilSkalar:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()

Matriks awal:
[[1 0 0 2]
 [0 1 0 5]
 [0 0 1 4]
 [0 0 0 1]]
Masukkan nilai skalar: 2
Matriks setelah operasi skalar:
[2, 0, 0, 4]
[0, 2, 0, 10]
[0, 0, 2, 8]
[0, 0, 0, 1]


**Rotasi**

Terhadap sumbu Z (Rz)

In [13]:
def rotasiSumbuZ(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[math.cos(totalRad), -math.sin(totalRad), 0, 0],
                             [math.sin(totalRad), math.cos(totalRad), 0, 0],
                             [0, 0, 1, 0],
                             [0, 0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 0, 2],
                            [0, 1, 0, 5],
                            [0, 0, 1, 4],
                            [0, 0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    hasilRotasi = rotasiSumbuZ(matriksAwal, sudutTotal, 0)

    print("Matriks setelah rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 0 2]
 [0 1 0 5]
 [0 0 1 4]
 [0 0 0 1]]
Masukkan sudut rotasi total (dalam derajat): 45
Matriks setelah rotasi:
[0.71, -0.71, 0.0, -2.12]
[0.71, 0.71, 0.0, 4.95]
[0.0, 0.0, 1.0, 4.0]
[0.0, 0.0, 0.0, 1.0]


Terhadap sumbu Y (Ry)

In [14]:
def rotasiSumbuY(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[math.cos(totalRad), 0, math.sin(totalRad), 0],
                             [0, 1, 0, 0],
                             [-math.sin(totalRad), 0, math.cos(totalRad), 0],
                             [0, 0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 0, 2],
                            [0, 1, 0, 5],
                            [0, 0, 1, 4],
                            [0, 0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    hasilRotasi = rotasiSumbuY(matriksAwal, sudutTotal, 0)

    print("Matriks setelah rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 0 2]
 [0 1 0 5]
 [0 0 1 4]
 [0 0 0 1]]
Masukkan sudut rotasi total (dalam derajat): 45
Matriks setelah rotasi:
[0.71, 0.0, 0.71, 4.24]
[0.0, 1.0, 0.0, 5.0]
[-0.71, 0.0, 0.71, 1.41]
[0.0, 0.0, 0.0, 1.0]


Terhadap sumbu X (Rx)

In [16]:
def rotasiSumbuX(matriks, sudut1, sudut2):
    totalRad = math.radians(sudut1 + sudut2)

    rotasiMatrix = np.array([[1, 0, 0, 0],
                             [0, math.cos(totalRad), -math.sin(totalRad), 0],
                             [0, math.sin(totalRad), math.cos(totalRad), 0],
                             [0, 0, 0, 1]])

    hasil = np.dot(rotasiMatrix, matriks)

    return hasil

def main():
    matriksAwal = np.array([[1, 0, 0, 2],
                            [0, 1, 0, 5],
                            [0, 0, 1, 4],
                            [0, 0, 0, 1]])

    print("Matriks awal:")
    print(matriksAwal)

    sudutTotal = float(input("Masukkan sudut rotasi total (dalam derajat): "))

    hasilRotasi = rotasiSumbuX(matriksAwal, sudutTotal, 0)

    print("Matriks setelah rotasi:")
    for row in hasilRotasi:
        print([round(val, 2) for val in row])

if __name__ == "__main__":
    main()


Matriks awal:
[[1 0 0 2]
 [0 1 0 5]
 [0 0 1 4]
 [0 0 0 1]]
Masukkan sudut rotasi total (dalam derajat): 45
Matriks setelah rotasi:
[1.0, 0.0, 0.0, 2.0]
[0.0, 0.71, -0.71, 0.71]
[0.0, 0.71, 0.71, 6.36]
[0.0, 0.0, 0.0, 1.0]
